# Generated by Django 4.1.1 on 2022-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotel_hotelroomfacility_hotelroom_generalfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfacility',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_general_facility', to='api.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='api.hotel'),
        ),
    ]
